
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TransactionType = {
  ON_RAMP: 'ON_RAMP',
  P2P: 'P2P'
} as const

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]


export const TransactionDirection = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
} as const

export type TransactionDirection = (typeof TransactionDirection)[keyof typeof TransactionDirection]


export const TransactionStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED'
} as const

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus]
