
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AppTransaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model AppTransaction
 * 
 */
export type AppTransactionModel = runtime.Types.Result.DefaultSelection<Prisma.$AppTransactionPayload>

export type AggregateAppTransaction = {
  _count: AppTransactionCountAggregateOutputType | null
  _avg: AppTransactionAvgAggregateOutputType | null
  _sum: AppTransactionSumAggregateOutputType | null
  _min: AppTransactionMinAggregateOutputType | null
  _max: AppTransactionMaxAggregateOutputType | null
}

export type AppTransactionAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  amount: number | null
}

export type AppTransactionSumAggregateOutputType = {
  id: number | null
  userId: number | null
  amount: number | null
}

export type AppTransactionMinAggregateOutputType = {
  id: number | null
  userId: number | null
  amount: number | null
  type: $Enums.TransactionType | null
  direction: $Enums.TransactionDirection | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
}

export type AppTransactionMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  amount: number | null
  type: $Enums.TransactionType | null
  direction: $Enums.TransactionDirection | null
  status: $Enums.TransactionStatus | null
  createdAt: Date | null
}

export type AppTransactionCountAggregateOutputType = {
  id: number
  userId: number
  amount: number
  type: number
  direction: number
  status: number
  createdAt: number
  _all: number
}


export type AppTransactionAvgAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
}

export type AppTransactionSumAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
}

export type AppTransactionMinAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  type?: true
  direction?: true
  status?: true
  createdAt?: true
}

export type AppTransactionMaxAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  type?: true
  direction?: true
  status?: true
  createdAt?: true
}

export type AppTransactionCountAggregateInputType = {
  id?: true
  userId?: true
  amount?: true
  type?: true
  direction?: true
  status?: true
  createdAt?: true
  _all?: true
}

export type AppTransactionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppTransaction to aggregate.
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppTransactions to fetch.
   */
  orderBy?: Prisma.AppTransactionOrderByWithRelationInput | Prisma.AppTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppTransactions
  **/
  _count?: true | AppTransactionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AppTransactionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AppTransactionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppTransactionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppTransactionMaxAggregateInputType
}

export type GetAppTransactionAggregateType<T extends AppTransactionAggregateArgs> = {
      [P in keyof T & keyof AggregateAppTransaction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppTransaction[P]>
    : Prisma.GetScalarType<T[P], AggregateAppTransaction[P]>
}




export type AppTransactionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppTransactionWhereInput
  orderBy?: Prisma.AppTransactionOrderByWithAggregationInput | Prisma.AppTransactionOrderByWithAggregationInput[]
  by: Prisma.AppTransactionScalarFieldEnum[] | Prisma.AppTransactionScalarFieldEnum
  having?: Prisma.AppTransactionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppTransactionCountAggregateInputType | true
  _avg?: AppTransactionAvgAggregateInputType
  _sum?: AppTransactionSumAggregateInputType
  _min?: AppTransactionMinAggregateInputType
  _max?: AppTransactionMaxAggregateInputType
}

export type AppTransactionGroupByOutputType = {
  id: number
  userId: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt: Date
  _count: AppTransactionCountAggregateOutputType | null
  _avg: AppTransactionAvgAggregateOutputType | null
  _sum: AppTransactionSumAggregateOutputType | null
  _min: AppTransactionMinAggregateOutputType | null
  _max: AppTransactionMaxAggregateOutputType | null
}

type GetAppTransactionGroupByPayload<T extends AppTransactionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppTransactionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppTransactionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppTransactionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppTransactionGroupByOutputType[P]>
      }
    >
  >



export type AppTransactionWhereInput = {
  AND?: Prisma.AppTransactionWhereInput | Prisma.AppTransactionWhereInput[]
  OR?: Prisma.AppTransactionWhereInput[]
  NOT?: Prisma.AppTransactionWhereInput | Prisma.AppTransactionWhereInput[]
  id?: Prisma.IntFilter<"AppTransaction"> | number
  userId?: Prisma.IntFilter<"AppTransaction"> | number
  amount?: Prisma.IntFilter<"AppTransaction"> | number
  type?: Prisma.EnumTransactionTypeFilter<"AppTransaction"> | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFilter<"AppTransaction"> | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFilter<"AppTransaction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"AppTransaction"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  onRamp?: Prisma.XOR<Prisma.OnRampTransactionNullableScalarRelationFilter, Prisma.OnRampTransactionWhereInput> | null
  p2p?: Prisma.XOR<Prisma.P2PTransactionNullableScalarRelationFilter, Prisma.P2PTransactionWhereInput> | null
}

export type AppTransactionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  onRamp?: Prisma.OnRampTransactionOrderByWithRelationInput
  p2p?: Prisma.P2PTransactionOrderByWithRelationInput
}

export type AppTransactionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.AppTransactionWhereInput | Prisma.AppTransactionWhereInput[]
  OR?: Prisma.AppTransactionWhereInput[]
  NOT?: Prisma.AppTransactionWhereInput | Prisma.AppTransactionWhereInput[]
  userId?: Prisma.IntFilter<"AppTransaction"> | number
  amount?: Prisma.IntFilter<"AppTransaction"> | number
  type?: Prisma.EnumTransactionTypeFilter<"AppTransaction"> | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFilter<"AppTransaction"> | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFilter<"AppTransaction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"AppTransaction"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  onRamp?: Prisma.XOR<Prisma.OnRampTransactionNullableScalarRelationFilter, Prisma.OnRampTransactionWhereInput> | null
  p2p?: Prisma.XOR<Prisma.P2PTransactionNullableScalarRelationFilter, Prisma.P2PTransactionWhereInput> | null
}, "id">

export type AppTransactionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AppTransactionCountOrderByAggregateInput
  _avg?: Prisma.AppTransactionAvgOrderByAggregateInput
  _max?: Prisma.AppTransactionMaxOrderByAggregateInput
  _min?: Prisma.AppTransactionMinOrderByAggregateInput
  _sum?: Prisma.AppTransactionSumOrderByAggregateInput
}

export type AppTransactionScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppTransactionScalarWhereWithAggregatesInput | Prisma.AppTransactionScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppTransactionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppTransactionScalarWhereWithAggregatesInput | Prisma.AppTransactionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AppTransaction"> | number
  userId?: Prisma.IntWithAggregatesFilter<"AppTransaction"> | number
  amount?: Prisma.IntWithAggregatesFilter<"AppTransaction"> | number
  type?: Prisma.EnumTransactionTypeWithAggregatesFilter<"AppTransaction"> | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionWithAggregatesFilter<"AppTransaction"> | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusWithAggregatesFilter<"AppTransaction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AppTransaction"> | Date | string
}

export type AppTransactionCreateInput = {
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTransactionsInput
  onRamp?: Prisma.OnRampTransactionCreateNestedOneWithoutTransactionInput
  p2p?: Prisma.P2PTransactionCreateNestedOneWithoutTransactionInput
}

export type AppTransactionUncheckedCreateInput = {
  id?: number
  userId: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedCreateNestedOneWithoutTransactionInput
  p2p?: Prisma.P2PTransactionUncheckedCreateNestedOneWithoutTransactionInput
}

export type AppTransactionUpdateInput = {
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTransactionsNestedInput
  onRamp?: Prisma.OnRampTransactionUpdateOneWithoutTransactionNestedInput
  p2p?: Prisma.P2PTransactionUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedUpdateOneWithoutTransactionNestedInput
  p2p?: Prisma.P2PTransactionUncheckedUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionCreateManyInput = {
  id?: number
  userId: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
}

export type AppTransactionUpdateManyMutationInput = {
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppTransactionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppTransactionListRelationFilter = {
  every?: Prisma.AppTransactionWhereInput
  some?: Prisma.AppTransactionWhereInput
  none?: Prisma.AppTransactionWhereInput
}

export type AppTransactionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppTransactionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AppTransactionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type AppTransactionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AppTransactionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  type?: Prisma.SortOrder
  direction?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AppTransactionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
}

export type AppTransactionScalarRelationFilter = {
  is?: Prisma.AppTransactionWhereInput
  isNot?: Prisma.AppTransactionWhereInput
}

export type AppTransactionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput> | Prisma.AppTransactionCreateWithoutUserInput[] | Prisma.AppTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutUserInput | Prisma.AppTransactionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AppTransactionCreateManyUserInputEnvelope
  connect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
}

export type AppTransactionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput> | Prisma.AppTransactionCreateWithoutUserInput[] | Prisma.AppTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutUserInput | Prisma.AppTransactionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AppTransactionCreateManyUserInputEnvelope
  connect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
}

export type AppTransactionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput> | Prisma.AppTransactionCreateWithoutUserInput[] | Prisma.AppTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutUserInput | Prisma.AppTransactionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AppTransactionUpsertWithWhereUniqueWithoutUserInput | Prisma.AppTransactionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AppTransactionCreateManyUserInputEnvelope
  set?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  disconnect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  delete?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  connect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  update?: Prisma.AppTransactionUpdateWithWhereUniqueWithoutUserInput | Prisma.AppTransactionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AppTransactionUpdateManyWithWhereWithoutUserInput | Prisma.AppTransactionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AppTransactionScalarWhereInput | Prisma.AppTransactionScalarWhereInput[]
}

export type AppTransactionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput> | Prisma.AppTransactionCreateWithoutUserInput[] | Prisma.AppTransactionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutUserInput | Prisma.AppTransactionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AppTransactionUpsertWithWhereUniqueWithoutUserInput | Prisma.AppTransactionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AppTransactionCreateManyUserInputEnvelope
  set?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  disconnect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  delete?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  connect?: Prisma.AppTransactionWhereUniqueInput | Prisma.AppTransactionWhereUniqueInput[]
  update?: Prisma.AppTransactionUpdateWithWhereUniqueWithoutUserInput | Prisma.AppTransactionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AppTransactionUpdateManyWithWhereWithoutUserInput | Prisma.AppTransactionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AppTransactionScalarWhereInput | Prisma.AppTransactionScalarWhereInput[]
}

export type EnumTransactionTypeFieldUpdateOperationsInput = {
  set?: $Enums.TransactionType
}

export type EnumTransactionDirectionFieldUpdateOperationsInput = {
  set?: $Enums.TransactionDirection
}

export type EnumTransactionStatusFieldUpdateOperationsInput = {
  set?: $Enums.TransactionStatus
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type AppTransactionCreateNestedOneWithoutOnRampInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutOnRampInput, Prisma.AppTransactionUncheckedCreateWithoutOnRampInput>
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutOnRampInput
  connect?: Prisma.AppTransactionWhereUniqueInput
}

export type AppTransactionUpdateOneRequiredWithoutOnRampNestedInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutOnRampInput, Prisma.AppTransactionUncheckedCreateWithoutOnRampInput>
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutOnRampInput
  upsert?: Prisma.AppTransactionUpsertWithoutOnRampInput
  connect?: Prisma.AppTransactionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppTransactionUpdateToOneWithWhereWithoutOnRampInput, Prisma.AppTransactionUpdateWithoutOnRampInput>, Prisma.AppTransactionUncheckedUpdateWithoutOnRampInput>
}

export type AppTransactionCreateNestedOneWithoutP2pInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutP2pInput, Prisma.AppTransactionUncheckedCreateWithoutP2pInput>
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutP2pInput
  connect?: Prisma.AppTransactionWhereUniqueInput
}

export type AppTransactionUpdateOneRequiredWithoutP2pNestedInput = {
  create?: Prisma.XOR<Prisma.AppTransactionCreateWithoutP2pInput, Prisma.AppTransactionUncheckedCreateWithoutP2pInput>
  connectOrCreate?: Prisma.AppTransactionCreateOrConnectWithoutP2pInput
  upsert?: Prisma.AppTransactionUpsertWithoutP2pInput
  connect?: Prisma.AppTransactionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppTransactionUpdateToOneWithWhereWithoutP2pInput, Prisma.AppTransactionUpdateWithoutP2pInput>, Prisma.AppTransactionUncheckedUpdateWithoutP2pInput>
}

export type AppTransactionCreateWithoutUserInput = {
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  onRamp?: Prisma.OnRampTransactionCreateNestedOneWithoutTransactionInput
  p2p?: Prisma.P2PTransactionCreateNestedOneWithoutTransactionInput
}

export type AppTransactionUncheckedCreateWithoutUserInput = {
  id?: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedCreateNestedOneWithoutTransactionInput
  p2p?: Prisma.P2PTransactionUncheckedCreateNestedOneWithoutTransactionInput
}

export type AppTransactionCreateOrConnectWithoutUserInput = {
  where: Prisma.AppTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput>
}

export type AppTransactionCreateManyUserInputEnvelope = {
  data: Prisma.AppTransactionCreateManyUserInput | Prisma.AppTransactionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AppTransactionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AppTransactionWhereUniqueInput
  update: Prisma.XOR<Prisma.AppTransactionUpdateWithoutUserInput, Prisma.AppTransactionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutUserInput, Prisma.AppTransactionUncheckedCreateWithoutUserInput>
}

export type AppTransactionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AppTransactionWhereUniqueInput
  data: Prisma.XOR<Prisma.AppTransactionUpdateWithoutUserInput, Prisma.AppTransactionUncheckedUpdateWithoutUserInput>
}

export type AppTransactionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AppTransactionScalarWhereInput
  data: Prisma.XOR<Prisma.AppTransactionUpdateManyMutationInput, Prisma.AppTransactionUncheckedUpdateManyWithoutUserInput>
}

export type AppTransactionScalarWhereInput = {
  AND?: Prisma.AppTransactionScalarWhereInput | Prisma.AppTransactionScalarWhereInput[]
  OR?: Prisma.AppTransactionScalarWhereInput[]
  NOT?: Prisma.AppTransactionScalarWhereInput | Prisma.AppTransactionScalarWhereInput[]
  id?: Prisma.IntFilter<"AppTransaction"> | number
  userId?: Prisma.IntFilter<"AppTransaction"> | number
  amount?: Prisma.IntFilter<"AppTransaction"> | number
  type?: Prisma.EnumTransactionTypeFilter<"AppTransaction"> | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFilter<"AppTransaction"> | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFilter<"AppTransaction"> | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFilter<"AppTransaction"> | Date | string
}

export type AppTransactionCreateWithoutOnRampInput = {
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTransactionsInput
  p2p?: Prisma.P2PTransactionCreateNestedOneWithoutTransactionInput
}

export type AppTransactionUncheckedCreateWithoutOnRampInput = {
  id?: number
  userId: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  p2p?: Prisma.P2PTransactionUncheckedCreateNestedOneWithoutTransactionInput
}

export type AppTransactionCreateOrConnectWithoutOnRampInput = {
  where: Prisma.AppTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutOnRampInput, Prisma.AppTransactionUncheckedCreateWithoutOnRampInput>
}

export type AppTransactionUpsertWithoutOnRampInput = {
  update: Prisma.XOR<Prisma.AppTransactionUpdateWithoutOnRampInput, Prisma.AppTransactionUncheckedUpdateWithoutOnRampInput>
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutOnRampInput, Prisma.AppTransactionUncheckedCreateWithoutOnRampInput>
  where?: Prisma.AppTransactionWhereInput
}

export type AppTransactionUpdateToOneWithWhereWithoutOnRampInput = {
  where?: Prisma.AppTransactionWhereInput
  data: Prisma.XOR<Prisma.AppTransactionUpdateWithoutOnRampInput, Prisma.AppTransactionUncheckedUpdateWithoutOnRampInput>
}

export type AppTransactionUpdateWithoutOnRampInput = {
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTransactionsNestedInput
  p2p?: Prisma.P2PTransactionUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionUncheckedUpdateWithoutOnRampInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  p2p?: Prisma.P2PTransactionUncheckedUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionCreateWithoutP2pInput = {
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutTransactionsInput
  onRamp?: Prisma.OnRampTransactionCreateNestedOneWithoutTransactionInput
}

export type AppTransactionUncheckedCreateWithoutP2pInput = {
  id?: number
  userId: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedCreateNestedOneWithoutTransactionInput
}

export type AppTransactionCreateOrConnectWithoutP2pInput = {
  where: Prisma.AppTransactionWhereUniqueInput
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutP2pInput, Prisma.AppTransactionUncheckedCreateWithoutP2pInput>
}

export type AppTransactionUpsertWithoutP2pInput = {
  update: Prisma.XOR<Prisma.AppTransactionUpdateWithoutP2pInput, Prisma.AppTransactionUncheckedUpdateWithoutP2pInput>
  create: Prisma.XOR<Prisma.AppTransactionCreateWithoutP2pInput, Prisma.AppTransactionUncheckedCreateWithoutP2pInput>
  where?: Prisma.AppTransactionWhereInput
}

export type AppTransactionUpdateToOneWithWhereWithoutP2pInput = {
  where?: Prisma.AppTransactionWhereInput
  data: Prisma.XOR<Prisma.AppTransactionUpdateWithoutP2pInput, Prisma.AppTransactionUncheckedUpdateWithoutP2pInput>
}

export type AppTransactionUpdateWithoutP2pInput = {
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutTransactionsNestedInput
  onRamp?: Prisma.OnRampTransactionUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionUncheckedUpdateWithoutP2pInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionCreateManyUserInput = {
  id?: number
  amount: number
  type: $Enums.TransactionType
  direction: $Enums.TransactionDirection
  status: $Enums.TransactionStatus
  createdAt?: Date | string
}

export type AppTransactionUpdateWithoutUserInput = {
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  onRamp?: Prisma.OnRampTransactionUpdateOneWithoutTransactionNestedInput
  p2p?: Prisma.P2PTransactionUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  onRamp?: Prisma.OnRampTransactionUncheckedUpdateOneWithoutTransactionNestedInput
  p2p?: Prisma.P2PTransactionUncheckedUpdateOneWithoutTransactionNestedInput
}

export type AppTransactionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.EnumTransactionTypeFieldUpdateOperationsInput | $Enums.TransactionType
  direction?: Prisma.EnumTransactionDirectionFieldUpdateOperationsInput | $Enums.TransactionDirection
  status?: Prisma.EnumTransactionStatusFieldUpdateOperationsInput | $Enums.TransactionStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AppTransactionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  type?: boolean
  direction?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  onRamp?: boolean | Prisma.AppTransaction$onRampArgs<ExtArgs>
  p2p?: boolean | Prisma.AppTransaction$p2pArgs<ExtArgs>
}, ExtArgs["result"]["appTransaction"]>

export type AppTransactionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  type?: boolean
  direction?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appTransaction"]>

export type AppTransactionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  amount?: boolean
  type?: boolean
  direction?: boolean
  status?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appTransaction"]>

export type AppTransactionSelectScalar = {
  id?: boolean
  userId?: boolean
  amount?: boolean
  type?: boolean
  direction?: boolean
  status?: boolean
  createdAt?: boolean
}

export type AppTransactionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "amount" | "type" | "direction" | "status" | "createdAt", ExtArgs["result"]["appTransaction"]>
export type AppTransactionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  onRamp?: boolean | Prisma.AppTransaction$onRampArgs<ExtArgs>
  p2p?: boolean | Prisma.AppTransaction$p2pArgs<ExtArgs>
}
export type AppTransactionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AppTransactionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AppTransactionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppTransaction"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    onRamp: Prisma.$OnRampTransactionPayload<ExtArgs> | null
    p2p: Prisma.$P2PTransactionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    amount: number
    type: $Enums.TransactionType
    direction: $Enums.TransactionDirection
    status: $Enums.TransactionStatus
    createdAt: Date
  }, ExtArgs["result"]["appTransaction"]>
  composites: {}
}

export type AppTransactionGetPayload<S extends boolean | null | undefined | AppTransactionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload, S>

export type AppTransactionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppTransactionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppTransactionCountAggregateInputType | true
  }

export interface AppTransactionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppTransaction'], meta: { name: 'AppTransaction' } }
  /**
   * Find zero or one AppTransaction that matches the filter.
   * @param {AppTransactionFindUniqueArgs} args - Arguments to find a AppTransaction
   * @example
   * // Get one AppTransaction
   * const appTransaction = await prisma.appTransaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppTransactionFindUniqueArgs>(args: Prisma.SelectSubset<T, AppTransactionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppTransaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppTransactionFindUniqueOrThrowArgs} args - Arguments to find a AppTransaction
   * @example
   * // Get one AppTransaction
   * const appTransaction = await prisma.appTransaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppTransactionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppTransactionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppTransaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionFindFirstArgs} args - Arguments to find a AppTransaction
   * @example
   * // Get one AppTransaction
   * const appTransaction = await prisma.appTransaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppTransactionFindFirstArgs>(args?: Prisma.SelectSubset<T, AppTransactionFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppTransaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionFindFirstOrThrowArgs} args - Arguments to find a AppTransaction
   * @example
   * // Get one AppTransaction
   * const appTransaction = await prisma.appTransaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppTransactionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppTransactionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppTransactions
   * const appTransactions = await prisma.appTransaction.findMany()
   * 
   * // Get first 10 AppTransactions
   * const appTransactions = await prisma.appTransaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appTransactionWithIdOnly = await prisma.appTransaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppTransactionFindManyArgs>(args?: Prisma.SelectSubset<T, AppTransactionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppTransaction.
   * @param {AppTransactionCreateArgs} args - Arguments to create a AppTransaction.
   * @example
   * // Create one AppTransaction
   * const AppTransaction = await prisma.appTransaction.create({
   *   data: {
   *     // ... data to create a AppTransaction
   *   }
   * })
   * 
   */
  create<T extends AppTransactionCreateArgs>(args: Prisma.SelectSubset<T, AppTransactionCreateArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppTransactions.
   * @param {AppTransactionCreateManyArgs} args - Arguments to create many AppTransactions.
   * @example
   * // Create many AppTransactions
   * const appTransaction = await prisma.appTransaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppTransactionCreateManyArgs>(args?: Prisma.SelectSubset<T, AppTransactionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppTransactions and returns the data saved in the database.
   * @param {AppTransactionCreateManyAndReturnArgs} args - Arguments to create many AppTransactions.
   * @example
   * // Create many AppTransactions
   * const appTransaction = await prisma.appTransaction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppTransactions and only return the `id`
   * const appTransactionWithIdOnly = await prisma.appTransaction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppTransactionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppTransactionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppTransaction.
   * @param {AppTransactionDeleteArgs} args - Arguments to delete one AppTransaction.
   * @example
   * // Delete one AppTransaction
   * const AppTransaction = await prisma.appTransaction.delete({
   *   where: {
   *     // ... filter to delete one AppTransaction
   *   }
   * })
   * 
   */
  delete<T extends AppTransactionDeleteArgs>(args: Prisma.SelectSubset<T, AppTransactionDeleteArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppTransaction.
   * @param {AppTransactionUpdateArgs} args - Arguments to update one AppTransaction.
   * @example
   * // Update one AppTransaction
   * const appTransaction = await prisma.appTransaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppTransactionUpdateArgs>(args: Prisma.SelectSubset<T, AppTransactionUpdateArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppTransactions.
   * @param {AppTransactionDeleteManyArgs} args - Arguments to filter AppTransactions to delete.
   * @example
   * // Delete a few AppTransactions
   * const { count } = await prisma.appTransaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppTransactionDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppTransactionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppTransactions
   * const appTransaction = await prisma.appTransaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppTransactionUpdateManyArgs>(args: Prisma.SelectSubset<T, AppTransactionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppTransactions and returns the data updated in the database.
   * @param {AppTransactionUpdateManyAndReturnArgs} args - Arguments to update many AppTransactions.
   * @example
   * // Update many AppTransactions
   * const appTransaction = await prisma.appTransaction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppTransactions and only return the `id`
   * const appTransactionWithIdOnly = await prisma.appTransaction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppTransactionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppTransactionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppTransaction.
   * @param {AppTransactionUpsertArgs} args - Arguments to update or create a AppTransaction.
   * @example
   * // Update or create a AppTransaction
   * const appTransaction = await prisma.appTransaction.upsert({
   *   create: {
   *     // ... data to create a AppTransaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppTransaction we want to update
   *   }
   * })
   */
  upsert<T extends AppTransactionUpsertArgs>(args: Prisma.SelectSubset<T, AppTransactionUpsertArgs<ExtArgs>>): Prisma.Prisma__AppTransactionClient<runtime.Types.Result.GetResult<Prisma.$AppTransactionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionCountArgs} args - Arguments to filter AppTransactions to count.
   * @example
   * // Count the number of AppTransactions
   * const count = await prisma.appTransaction.count({
   *   where: {
   *     // ... the filter for the AppTransactions we want to count
   *   }
   * })
  **/
  count<T extends AppTransactionCountArgs>(
    args?: Prisma.Subset<T, AppTransactionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppTransactionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppTransactionAggregateArgs>(args: Prisma.Subset<T, AppTransactionAggregateArgs>): Prisma.PrismaPromise<GetAppTransactionAggregateType<T>>

  /**
   * Group by AppTransaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppTransactionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppTransactionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppTransactionGroupByArgs['orderBy'] }
      : { orderBy?: AppTransactionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppTransactionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppTransactionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppTransaction model
 */
readonly fields: AppTransactionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppTransaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppTransactionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  onRamp<T extends Prisma.AppTransaction$onRampArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppTransaction$onRampArgs<ExtArgs>>): Prisma.Prisma__OnRampTransactionClient<runtime.Types.Result.GetResult<Prisma.$OnRampTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  p2p<T extends Prisma.AppTransaction$p2pArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppTransaction$p2pArgs<ExtArgs>>): Prisma.Prisma__P2PTransactionClient<runtime.Types.Result.GetResult<Prisma.$P2PTransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppTransaction model
 */
export interface AppTransactionFieldRefs {
  readonly id: Prisma.FieldRef<"AppTransaction", 'Int'>
  readonly userId: Prisma.FieldRef<"AppTransaction", 'Int'>
  readonly amount: Prisma.FieldRef<"AppTransaction", 'Int'>
  readonly type: Prisma.FieldRef<"AppTransaction", 'TransactionType'>
  readonly direction: Prisma.FieldRef<"AppTransaction", 'TransactionDirection'>
  readonly status: Prisma.FieldRef<"AppTransaction", 'TransactionStatus'>
  readonly createdAt: Prisma.FieldRef<"AppTransaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AppTransaction findUnique
 */
export type AppTransactionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter, which AppTransaction to fetch.
   */
  where: Prisma.AppTransactionWhereUniqueInput
}

/**
 * AppTransaction findUniqueOrThrow
 */
export type AppTransactionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter, which AppTransaction to fetch.
   */
  where: Prisma.AppTransactionWhereUniqueInput
}

/**
 * AppTransaction findFirst
 */
export type AppTransactionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter, which AppTransaction to fetch.
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppTransactions to fetch.
   */
  orderBy?: Prisma.AppTransactionOrderByWithRelationInput | Prisma.AppTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppTransactions.
   */
  cursor?: Prisma.AppTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppTransactions.
   */
  distinct?: Prisma.AppTransactionScalarFieldEnum | Prisma.AppTransactionScalarFieldEnum[]
}

/**
 * AppTransaction findFirstOrThrow
 */
export type AppTransactionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter, which AppTransaction to fetch.
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppTransactions to fetch.
   */
  orderBy?: Prisma.AppTransactionOrderByWithRelationInput | Prisma.AppTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppTransactions.
   */
  cursor?: Prisma.AppTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppTransactions.
   */
  distinct?: Prisma.AppTransactionScalarFieldEnum | Prisma.AppTransactionScalarFieldEnum[]
}

/**
 * AppTransaction findMany
 */
export type AppTransactionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter, which AppTransactions to fetch.
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppTransactions to fetch.
   */
  orderBy?: Prisma.AppTransactionOrderByWithRelationInput | Prisma.AppTransactionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppTransactions.
   */
  cursor?: Prisma.AppTransactionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppTransactions.
   */
  skip?: number
  distinct?: Prisma.AppTransactionScalarFieldEnum | Prisma.AppTransactionScalarFieldEnum[]
}

/**
 * AppTransaction create
 */
export type AppTransactionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * The data needed to create a AppTransaction.
   */
  data: Prisma.XOR<Prisma.AppTransactionCreateInput, Prisma.AppTransactionUncheckedCreateInput>
}

/**
 * AppTransaction createMany
 */
export type AppTransactionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppTransactions.
   */
  data: Prisma.AppTransactionCreateManyInput | Prisma.AppTransactionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AppTransaction createManyAndReturn
 */
export type AppTransactionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * The data used to create many AppTransactions.
   */
  data: Prisma.AppTransactionCreateManyInput | Prisma.AppTransactionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AppTransaction update
 */
export type AppTransactionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * The data needed to update a AppTransaction.
   */
  data: Prisma.XOR<Prisma.AppTransactionUpdateInput, Prisma.AppTransactionUncheckedUpdateInput>
  /**
   * Choose, which AppTransaction to update.
   */
  where: Prisma.AppTransactionWhereUniqueInput
}

/**
 * AppTransaction updateMany
 */
export type AppTransactionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppTransactions.
   */
  data: Prisma.XOR<Prisma.AppTransactionUpdateManyMutationInput, Prisma.AppTransactionUncheckedUpdateManyInput>
  /**
   * Filter which AppTransactions to update
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * Limit how many AppTransactions to update.
   */
  limit?: number
}

/**
 * AppTransaction updateManyAndReturn
 */
export type AppTransactionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * The data used to update AppTransactions.
   */
  data: Prisma.XOR<Prisma.AppTransactionUpdateManyMutationInput, Prisma.AppTransactionUncheckedUpdateManyInput>
  /**
   * Filter which AppTransactions to update
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * Limit how many AppTransactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AppTransaction upsert
 */
export type AppTransactionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * The filter to search for the AppTransaction to update in case it exists.
   */
  where: Prisma.AppTransactionWhereUniqueInput
  /**
   * In case the AppTransaction found by the `where` argument doesn't exist, create a new AppTransaction with this data.
   */
  create: Prisma.XOR<Prisma.AppTransactionCreateInput, Prisma.AppTransactionUncheckedCreateInput>
  /**
   * In case the AppTransaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppTransactionUpdateInput, Prisma.AppTransactionUncheckedUpdateInput>
}

/**
 * AppTransaction delete
 */
export type AppTransactionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
  /**
   * Filter which AppTransaction to delete.
   */
  where: Prisma.AppTransactionWhereUniqueInput
}

/**
 * AppTransaction deleteMany
 */
export type AppTransactionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppTransactions to delete
   */
  where?: Prisma.AppTransactionWhereInput
  /**
   * Limit how many AppTransactions to delete.
   */
  limit?: number
}

/**
 * AppTransaction.onRamp
 */
export type AppTransaction$onRampArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OnRampTransaction
   */
  select?: Prisma.OnRampTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OnRampTransaction
   */
  omit?: Prisma.OnRampTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OnRampTransactionInclude<ExtArgs> | null
  where?: Prisma.OnRampTransactionWhereInput
}

/**
 * AppTransaction.p2p
 */
export type AppTransaction$p2pArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the P2PTransaction
   */
  select?: Prisma.P2PTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the P2PTransaction
   */
  omit?: Prisma.P2PTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.P2PTransactionInclude<ExtArgs> | null
  where?: Prisma.P2PTransactionWhereInput
}

/**
 * AppTransaction without action
 */
export type AppTransactionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppTransaction
   */
  select?: Prisma.AppTransactionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppTransaction
   */
  omit?: Prisma.AppTransactionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppTransactionInclude<ExtArgs> | null
}
